# Generated by Django 4.1.1 on 2022-09-11 15:44

from django.db import migrations, models
import djongo.models.fields
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=70)),
                ('monday', djongo.models.fields.ArrayField(model_container=schedule.models.Course, model_form_class=schedule.models.CourseForm)),
                ('tuesday', djongo.models.fields.ArrayField(model_container=schedule.models.Course, model_form_class=schedule.models.CourseForm)),
                ('wednesday', djongo.models.fields.ArrayField(model_container=schedule.models.Course, model_form_class=schedule.models.CourseForm)),
                ('thursday', djongo.models.fields.ArrayField(model_container=schedule.models.Course, model_form_class=schedule.models.CourseForm)),
                ('friday', djongo.models.fields.ArrayField(model_container=schedule.models.Course, model_form_class=schedule.models.CourseForm)),
                ('saturday', djongo.models.fields.ArrayField(model_container=schedule.models.Course, model_form_class=schedule.models.CourseForm)),
            ],
        ),
    ]
